HomeWork. Lesson09
extensaman/JC pull request #1
Opened 2021-12-03 13:08 UTC by extensaman

Дано:
 *
 * Есть три типа студентов:
 * 1 тип - делают разборы, практическую часть и находятся в потоке
 * 2 тип - делают только практическую часть и разборы
 * 3 тип - делают только практическую часть
 *
 * У студентов есть талант: величина от 0,1 до 1. Талант влияет на освоение навыка(скила).
 * Например если для освоения навыка вождения нужно потратить 22 часа, то
 * студент с талантом 1 затратит 22 часа
 * студент с талантом 0,1 затратит 22/0,1 = 220 часов
 * студент с талантом 0,5 затратит 22/0,5 = 44 часа
 * студент с талантом 0,8 затратит 22/0,8 = 27,5 часов
 *
 * Считается что 1 тип студентов освайвают материал за то время, которое нужно потратить на освоение.
 * 2 тип студентов освайвают материал в два раза дольше.
 * 3 тип студентов освайвают материал в три раза дольше.
 * Например если для освоения навыка вождения нужно потратить 22 часа, то
 * 1 тип студента потратит 22 часа (22/3 = 7,3; 7,3 часа на разборы, 7,3 часа на практику, 7,3 часа на находение в потоке)
 * 2 тип студента потрати 22 x 2 = 44 часа (44/2 = 22; 22 часа на практику, 22 часа на разборы)
 * 3 тип студента потратит 22 x 3 = 66 часов (66 часов на практику)
 *
 * Задача:
 * Студенту 1 типа с талантом 1 нужно потратить на разбор для преобретения практического навыка по java core 66 часов
 * (Всего на освоение навыка по java core 198 часов).
 * Необходимо посчитать для каждого студента затраченное время на изучение java в классе
 * (вывести на экран тип студента, его талант, время необходимое для разбора, практики,
 * нахождения в потоке и суммарное время на освоение навыка).
 *
 * В классе 9 студентов (по 3 студента каждого типа).
 * Талант задается рандомно.
 * Использовать патерн стратегия.

2021-12-05 08:59 UTC, Vlasik-Henadzi requested changes

2021-12-05 08:59 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Group.java
> +    public static final int GROUP_CAPACITY = 9;
это в раннер выноси, там задается размер группы

2021-12-05 08:59 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Group.java
> +        group = new Student[GROUP_CAPACITY];
размер группы через конструктор задавай

2021-12-05 08:59 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Student.java
> +    public static final int FULL_TIME_FOR_BEST_STUDENT = 198;
вынести в ранер, оттуда задавать время для конкретной программы

2021-12-05 08:59 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Student.java
> +        this.talantLevel = ((int) (Math.random() * 10.0) + 1) / 10.0;
Создай утилитный класс с методом для выдачи рандомного таланта, и передавать талант студенты через конструктор

2021-12-05 08:59 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Type01Student.java
> +        double time = FULL_TIME_FOR_BEST_STUDENT / 3.0;
задавать через конструктор

2021-12-05 08:59 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Student.java
> +                "\nСумарное время на освоение навыка: " + resultable.calculateSummaryTime(this) +
toString обычно выводят поля класса
методы для подсчета  времени, лучше сдеалть метод в классе Student который будет вызывать
resultable.calculateSummaryTime(this) 
Или создать интерфейс  resultable который имеет три метода calculateRasbor, calculatePotok, calculatePractice
и в каждом типе студента реализовать эти методы
Патерн стратегия реализовать в Group, массив групы формировать передавать из вне в конструктор.

2021-12-05 20:43 UTC, Vlasik-Henadzi approved these changes

2021-12-05 20:43 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Logic.java
> +    public Student simpleFactory (StudentTypes studentType) {
можно делать статический метод

2021-12-05 20:43 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/Logic.java
> +    public Student[] formGroup (int capacity) {
можно делать статический метод

2021-12-05 20:43 UTC, Vlasik-Henadzi commented on src/home/chapter06inheritance/task01/StudentTalant.java
> +    public double generateTalantLevel() {
я бы сделал статический метод и каждый раз при его вызове
возвращал рандмынй талант

2021-12-06 07:30 UTC, extensaman commented on src/home/chapter06inheritance/task01/Logic.java
> +    public Student simpleFactory (StudentTypes studentType) {
Fixed

2021-12-06 07:30 UTC, extensaman commented on src/home/chapter06inheritance/task01/Logic.java
> +    public Student[] formGroup (int capacity) {
Fixed

2021-12-06 07:30 UTC, extensaman commented on src/home/chapter06inheritance/task01/StudentTalant.java
> +    public double generateTalantLevel() {
Fixed

2021-12-06 07:31 UTC, merged